# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build --pull -t "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA" .
    - docker image tag "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-latest"
    - docker push "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-latest"
